apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ude-oslo-kommune-no
resources:
  - ../../../base
patchesStrategicMerge:
  - config-map.yaml
  - fint-client.yaml
commonLabels:
  app.kubernetes.io/name: fint-utdanning-larling-adapter
  app.kubernetes.io/instance: fint-utdanning-larling-adapter_ude-oslo-kommune-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: ude.oslo.kommune.no