fint:
  adapter:
    id: https://vigoiks.no/fintlabs-no/utdanning/vurdering
    password:
    username:
    base-url: https://alpha.felleskomponent.no
    registration-id: fint
    org-id: fintlabs.no
    heartbeat-interval: 1
    capabilities:
      larling:
        domain-name: utdanning
        packageName: larling
        resource-name: larling
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      person:
        domain-name: felles
        packageName:
        resource-name: person
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE
      virksomhet:
        domain-name: felles
        packageName:
        resource-name: virksomhet
        fullSyncIntervalInDays: 1
        deltaSyncInterval: IMMEDIATE

spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-adapter
