apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-utdanning-larling-adapter
  app.kubernetes.io/instance: fint-utdanning-larling-adapter_trondelagfylke_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: adapter
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: trondelagfylke.no

patches:
  - path: config-map.yaml
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-utdanning-larling-adapter_trondelagfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
    target:
      kind: FintClient
      name: fint-utdanning-larling-adapter